import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../data/models/patient_report_model.dart';

final patientReportsStreamProvider = StreamProvider.family<List<PatientReportModel>, String>((ref, patientId) {
  return FirebaseFirestore.instance
      .collection('patients')
      .doc(patientId)
      .collection('reports')
      .orderBy('generatedAt', descending: true)
      .snapshots()
      .map((snap) => snap.docs.map((doc) => PatientReportModel.fromFirestore(doc)).toList());
});

class PatientReportController extends StateNotifier<AsyncValue<void>> {
  PatientReportController() : super(const AsyncValue.data(null));

  Future<void> saveReport({
    required String patientId,
    required String reportName,
    required String reportType,
    required String generatedBy,
    required String reportPeriod,
  }) async {
    state = const AsyncValue.loading();
    try {
      final docRef = FirebaseFirestore.instance
          .collection('patients')
          .doc(patientId)
          .collection('reports')
          .doc();

      final batch = FirebaseFirestore.instance.batch();

      batch.set(docRef, {
        'reportName': reportName,
        'reportType': reportType,
        'generatedAt': FieldValue.serverTimestamp(),
        'generatedBy': generatedBy,
        'reportPeriod': reportPeriod,
        'pdfUrl': 'reports/${docRef.id}.pdf',
        'patientId': patientId,
      });

      // Add to patient history
      final historyRef = FirebaseFirestore.instance
          .collection('patients')
          .doc(patientId)
          .collection('history')
          .doc();

      batch.set(historyRef, {
        'event': 'Report "$reportName" Generated by $generatedBy',
        'type': 'report_generated',
        'createdAt': FieldValue.serverTimestamp(),
      });

      await batch.commit();
      state = const AsyncValue.data(null);
    } catch (e, st) {
      state = AsyncValue.error(e, st);
      rethrow;
    }
  }

  Future<void> logReportPrinted({
    required String patientId,
    required String reportName,
    required String nurseName,
  }) async {
    try {
      await FirebaseFirestore.instance
          .collection('patients')
          .doc(patientId)
          .collection('history')
          .add({
        'event': 'Report "$reportName" Printed by $nurseName',
        'type': 'report_printed',
        'createdAt': FieldValue.serverTimestamp(),
      });
    } catch (_) {}
  }
}

final patientReportControllerProvider = StateNotifierProvider<PatientReportController, AsyncValue<void>>((ref) {
  return PatientReportController();
});
