// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD5wtpgtouTKdARN32DgpYcm5KvbNVn3q8',
    appId: '1:120558203904:web:a903f2873a8d768070d4e5',
    messagingSenderId: '120558203904',
    projectId: 'shifa-home-health-care',
    authDomain: 'shifa-home-health-care.firebaseapp.com',
    databaseURL: 'https://shifa-home-health-care-default-rtdb.firebaseio.com',
    storageBucket: 'shifa-home-health-care.firebasestorage.app',
    measurementId: 'G-84305Y0N1B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpCQYyjVPbCwo4DouQ0Wy0_ib7kFwOm9Y',
    appId: '1:120558203904:android:f525915540ff130f70d4e5',
    messagingSenderId: '120558203904',
    projectId: 'shifa-home-health-care',
    databaseURL: 'https://shifa-home-health-care-default-rtdb.firebaseio.com',
    storageBucket: 'shifa-home-health-care.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpCQYyjVPbCwo4DouQ0Wy0_ib7kFwOm9Y',
    appId: '1:120558203904:ios:a903f2873a8d768070d4e5',
    messagingSenderId: '120558203904',
    projectId: 'shifa-home-health-care',
    databaseURL: 'https://shifa-home-health-care-default-rtdb.firebaseio.com',
    storageBucket: 'shifa-home-health-care.firebasestorage.app',
    iosBundleId: 'com.shifa.homehealthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpCQYyjVPbCwo4DouQ0Wy0_ib7kFwOm9Y',
    appId: '1:120558203904:ios:a903f2873a8d768070d4e5',
    messagingSenderId: '120558203904',
    projectId: 'shifa-home-health-care',
    databaseURL: 'https://shifa-home-health-care-default-rtdb.firebaseio.com',
    storageBucket: 'shifa-home-health-care.firebasestorage.app',
    iosBundleId: 'com.shifa.homehealthcare',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD5wtpgtouTKdARN32DgpYcm5KvbNVn3q8',
    appId: '1:120558203904:web:a903f2873a8d768070d4e5',
    messagingSenderId: '120558203904',
    projectId: 'shifa-home-health-care',
    authDomain: 'shifa-home-health-care.firebaseapp.com',
    databaseURL: 'https://shifa-home-health-care-default-rtdb.firebaseio.com',
    storageBucket: 'shifa-home-health-care.firebasestorage.app',
    measurementId: 'G-84305Y0N1B',
  );
}