# Set platform to 13.0 for modern Flutter support
platform :ios, '13.0'

# CocoaPods analytics sends network stats. If you want to disable this, uncomment the following line.
# disable_cocoapods_analytics!

# Load Flutter podhelper
flutter_ios_podfile_setup = File.join(File.dirname(File.realpath(__FILE__)), 'Flutter', 'podhelper.rb')
require flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    
    # Fix Xcode 15+ / iOS arm64 BoringSSL compiler flag crash
    if target.name == 'BoringSSL-GRPC'
      target.source_build_phase.files.each do |file|
        if file.settings && file.settings['COMPILER_FLAGS']
          flags = file.settings['COMPILER_FLAGS'].split
          flags.reject! { |flag| flag == '-GCC_WARN_INHIBIT_ALL_WARNINGS' }
          file.settings['COMPILER_FLAGS'] = flags.join(' ')
        end
      end
    end
  end
end
